
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jul  8 2025 02:57:28 IST (Jul  7 2025 21:27:28 UTC)

// Verification Directory fv/up_counter 

module up_counter(clk, rst, count);
  input clk, rst;
  output [3:0] count;
  wire clk, rst;
  wire [3:0] count;
  wire n_0, n_1, n_3, n_4, n_10, n_15, n_17, n_20;
  wire n_21, n_23, n_25, n_26, n_27, n_31;
  DFFQXL \count_reg[3] (.CK (clk), .D (n_10), .Q (count[3]));
  NOR2X2 g173__2398(.A (n_27), .B (rst), .Y (n_10));
  DFFQXL \count_reg[1] (.CK (clk), .D (n_4), .Q (count[1]));
  NOR2X4 g181__5526(.A (n_1), .B (rst), .Y (n_4));
  DFFQXL \count_reg[0] (.CK (clk), .D (n_0), .Q (count[0]));
  XNOR2X1 g184__1617(.A (n_20), .B (n_17), .Y (n_1));
  NAND2XL g186__2802(.A (n_21), .B (n_17), .Y (n_3));
  NOR2X2 g185__1705(.A (n_20), .B (rst), .Y (n_0));
  CLKBUFX2 fopt192(.A (count[1]), .Y (n_17));
  CLKBUFX2 fopt193(.A (n_21), .Y (n_20));
  CLKBUFX2 fopt194(.A (count[0]), .Y (n_21));
  DLY2X1 fopt195(.A (count[3]), .Y (n_23));
  NOR2X4 g2(.A (n_25), .B (rst), .Y (n_26));
  XNOR2X1 g3(.A (n_15), .B (n_3), .Y (n_25));
  DFFXL \count_reg[2] (.CK (clk), .D (n_26), .Q (count[2]), .QN (n_15));
  CLKXOR2X1 g198(.A (n_23), .B (n_31), .Y (n_27));
  OR2X1 g200(.A (n_3), .B (n_15), .Y (n_31));
endmodule

