/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID vlsilab10.nitc.ac.in)
#  Generated on:      Sun Jul 20 02:44:15 2025
#  Design:            up_counter
#  Command:           saveNetlist /home/M24_2/cadence_edt/mokesh_new/physical_design_90/trial_new/lvs_1/up_counter.v -phys -includePowerGround -excludeLeafCell
###############################################################
*/
module up_counter (
	clk, 
	rst, 
	count);
   input clk;
   input rst;
   output [3:0] count;

   // Internal wires
   wire VSS;
   wire VDD;
   wire n_0;
   wire n_1;
   wire n_3;
   wire n_4;
   wire n_10;
   wire n_15;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_31;

   // Module instantiations
   DFFQXL \count_reg[3]  (
	.CK(clk),
	.D(n_10),
	.Q(count[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2 g173__2398 (
	.A(n_27),
	.B(rst),
	.Y(n_10), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFQXL \count_reg[1]  (
	.CK(clk),
	.D(n_4),
	.Q(count[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X4 g181__5526 (
	.A(n_1),
	.B(rst),
	.Y(n_4), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFQXL \count_reg[0]  (
	.CK(clk),
	.D(n_0),
	.Q(count[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1 g184__1617 (
	.A(count[0]),
	.B(count[1]),
	.Y(n_1), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2XL g186__2802 (
	.A(count[0]),
	.B(count[1]),
	.Y(n_3), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2 g185__1705 (
	.A(count[0]),
	.B(rst),
	.Y(n_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X4 g2 (
	.A(n_25),
	.B(rst),
	.Y(n_26), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1 g3 (
	.A(n_15),
	.B(n_3),
	.Y(n_25), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFXL \count_reg[2]  (
	.CK(clk),
	.D(n_26),
	.Q(count[2]),
	.QN(n_15), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKXOR2X1 g198 (
	.A(count[3]),
	.B(n_31),
	.Y(n_27), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X1 g200 (
	.A(n_3),
	.B(n_15),
	.Y(n_31), 
	.VSS(VSS), 
	.VDD(VDD));
endmodule

